- job-template: !include: deploy-image-generic.tmpl

- project:
    name: app-deploy
    jobs:
      - "{folder}/self-serve-deploy-app":
          folder: "Architect/YubiGPT/Int"
          env: qa
          service_name: yubiGPT
          namespace: yubigpt-qa
          app_repo: open-webui
          app_branch: main
          project: yubigpt
          helm_or_kubectl_apply: "sed -i "s|harbor.example.in/yubi/common-yubigpt:latest|harbor.example.in/yubi/common-yubigpt:${release_tag}|g" ../k8smanifest/open-webui.yaml;cat  ../k8smanifest/open-webui.yaml; kubectl apply -f ../k8smanifest/ -n {namespace}"
          k8s_manifest_repo: open-webui_manifest
          k8s_manifest_branch: master
