- job-template: !include: promote-to-environment.tmpl

- project:
    name: common-promote-docker
    jobs:
      - "{folder}/promote-to-{env}":
          folder: "DeveloperCommon/SelfServe/YubiGPT/Stg"
          env: qa
          service_name: yubigpt
          namespace: yubigpt-qa
          helm_or_kubectl_apply: "kubectl apply -f dir/*.yaml -n {namespace}"
          project: yubigpt
          app_org: credavenue
          app_repo: open-webui
          app_branch: main
          k8s_manifest_repo: open-webui_manifest
          k8s_manifest_branch: master
